### ISSUE TITLE
Add images, logos, and configure folders/files.

### ISSUE THREAD

**Issue by WrappedUsername** [WrappedUsername/wrappedusernames-portfolio#2]
## Todo

- [x] Add logos, and images.
- [x] Configure folders and files
- [x] Add MIT LICENSE file.
- [x] Update README file.
