### ISSUE TITLE
Integrate theme idea and create intersection observer for text fader.

### ISSUE THREAD

**Issue by WrappedUsername** [WrappedUsername/wrappedusernames-portfolio#6]
## Todo

- [x] Create intersection observers.
- [x] Create text fader on scroll.
- [x] Create fading portfolio cards on scroll.
- [x] Create fading about section.
- [x] Create seamless scrolling experience 💯

**Comment by WrappedUsername** [comment]
All tasks complete.
