### ISSUE TITLE
Integrate GraphQL, and Hygraph CMS for portfolio/featured repositories.

### ISSUE THREAD

**Issue by WrappedUsername** [WrappedUsername/wrappedusernames-portfolio#7]
## Todo 

- [x] Create services folder in root, for index.tsx file, for graphQL queries.
- [x] Create project in Hygraph CMS.
- [x] Create graphQL queries.
- [x] Create .env file API keys.

**Comment by WrappedUsername** [comment]
All tasks complete.
