### ISSUE TITLE
Responsive design needs work.

### ISSUE THREAD

**Issue by WrappedUsername** [WrappedUsername/wrappedusernames-portfolio#8]
## Todo

- [x] Fix bugs in small screen size.
- [x] Fix bugs in medium and above screen sizes.
- [x] align-middle for Hello World needs bug fix on all screen sizes.

**Comment by WrappedUsername** [comment]
I returned a header instead of div in Header.tsx

**Comment by WrappedUsername** [comment]
Medium screens and smaller responsive design not working.

**Comment by WrappedUsername** [comment]
I needed to make break points in my components.
